<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use DB;
use Illuminate\Database\Seeder;

class MovieTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('movies')->insert([
            [
            'movie_name'=> "The Batman",
            'genres' => json_encode([1,5]),
            'director' => "Matt Reeves",
            'producers' => "Warner Bros,DC Entertainment,6th & Idaho Productions",
            'writters' => "Matt Reeves,Peter Craig,Bob Kane",
            'actors' => "Robert Pattinson,Zoë Kravitz,Jeffrey Wright,Colin Farrell,Paul Dano",
            'description' => "Two years of nights have turned Bruce Wayne into a nocturnal animal. But as he continues to find his way as Gotham's dark knight Bruce is forced into a game of cat and mouse with his biggest threat so far, a manic killer known as The Riddler who is filled with rage and determined to expose the corrupt system whilst picking off all of Gotham's key political figures. Working with both established and new allies, Bruce must track down the killer and see him brought to justice, while investigating his father's true legacy and questioning the effect that he has had on Gotham so far as The Batman.",
            'movie_image' => "images/thebatman.jpg",	
            'trailer_link' => "https://imdb-video.media-imdb.com/vi3196175129/1434659607842-pgv4ql-1634416886363.mp4?Expires=1696755039&Signature=VDHq8CnqoQjYkC7gHPSdJEmNBlRUs6WinYw~4TGktDHj0lS1f5yQ0~o1lHZW7jxXKtvM8z9jrwDi~oHIydzDqjN4CYCYZlTiFIHLqm9Q4620ndMNevLgJZJfO53~a0PEbZSSkKZbqavwLizpZieZTfTJ3~d24LDKdES4mtI1AOtezyIMU4OOZ2HwyYJrnt-wLTtAiEal-OWXtMzSDXSE1gPJ2O-w226JtwOWumLWfOddM872BOl-wt-6lWzBiiS8E9IMOKjF4b7Rsh0We3~9rXXCIuRNs2iDVVOJEUuO7eBnMyRHmvtsl3YM-py~RCJu5oMZW4Ikf9blMTggtrG17A__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
            'rating' => 7.8,
            'release_date' => '04-03-2022',
            'runtime' => "2h 56m",
            'theatres' => "",
            'ott_platform' => "2",
            'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.f50f8c44-66ba-4e83-94bb-82fb40c52159",
            'imdb_id' => "tt1877830",
            'movie_link'=> "https://embed.smashystream.com/playere.php?imdb=tt1877830",
            ],

            [
             'movie_name'=> "Spider-Man: Across the Spider-Verse",
             'genres' => json_encode([1,5]),
             'director' => "Joaquim Dos Santos,Kemp Powers,Justin K. Thompson",
             'producers' => "Sony Pictures Animation,Marvel Entertainment,Arad Productions",
             'writters' => "Phil Lord,Christopher Miller,Dave Callaham",
             'actors' => "Shameik Moore,Hailee Steinfeld,Brian Tyree Henry,Oscar Isaac",
             'description' => "Miles Morales returns once again to save the multiverse! After being reunited with Gwen Stacy, Miles races across the multiverse to try and defeat a powerful foe known as the Spot. He meets many other spider people. But Miguel O'Hara doesn't approve of Miles' actions to save everyone, following canon events. He ends up on a run from Miguel and hundreds of other spider people. Will Miles save the multiverse? You're about to find out.",
             'movie_image' => "images/spiderman-across-the-spider-verse.jpg",	
             'trailer_link' => "https://imdb-video.media-imdb.com/vi872465433/1434659607842-pgv4ql-1680618823877.mp4?Expires=1696774225&Signature=DhDMLjbagz7Z84h0DwwbUs21ZpDKQLqM5E3lQifdMcp~Juz2CTn1ugDWe9OhQxf9sn-jVfIrl5pbGh89tCkkjgDbwTSFgQE0rGmaTec0qQiwlFAh5YmRT7tK4Gd6IbfK7BZS0M6EeN2bS0gGB7sVTrzoszA~chugq6S9PGXiNGgvjxQHL1kE4QxO5ueFxh0NeHWS0HYMWMmRA4G2jNJ7NUvYOCwdosRCtPsl6COONRq9A7TKdOnz5bFzHCu~JYGmS5NKybkDK5pWpNx7EUHvvXaJhoyjO-p0P7tr599XEvGvpqF4F3a3zm39mbPNVEGpKI4qyTLk3keLf-MZRjHmXw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
             'rating' => 8.7,
             'release_date' => '01-06-2023',
             'runtime' => "2h 20m",
             'theatres' => "",
             'ott_platform' => "2",
             'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.87f7ea62-3ae7-4236-b955-c1f21da58d91",
             'imdb_id' => "tt9362722",
             'movie_link'=> "https://embed.smashystream.com/playere.php?imdb=tt9362722"
            ],

            [
             'movie_name'=> "Jailer",
             'genres' => json_encode([1,8,9,3]),
             'director' => "Nelson Dilipkumar",
             'producers' => "Sun Pictures",
             'writters' => "Nelson Dilipkumar",
             'actors' => "Rajinikanth,Mohanlal,Shivarajkumar,Vinayakan,	Ramya Krishnan",
             'description' => "Muthuvel Pandian is a retired jailer living happily with his wife, son, daughter-in-law and grandson. His son who is an Assistant Commissioner of police goes missing while investigating the case of missing temple idols and is presumed dead. The story is about how Muthuvel Pandian goes toe to toe against Varma, the mastermind behind large-scale smuggling of temple idols and treasures, and avenges his son.",
             'movie_image' => "images/jailer.jpg",	
             'trailer_link' => "https://imdb-video.media-imdb.com/vi562611993/1434659607842-pgv4ql-1691502631740.mp4?Expires=1697131285&Signature=l3DDwZeo5pltjy95q~Z1l1MxcQQ2~M8biCw6D2lTQ3rHQl-jw8IAKAdPFo5QESdRLdLl3n3ZPuntJoQeJzmbPPJkAlt5l4hmtNZmUgb3p1c9OEU7l9WGh0gJbsQvbXSZozcosUtWi-nR7lNxF77T3JCgzEs3uIdjgmp7sZHghW98wAVL~8F9kcmv82AF88yNfmOmkQMDe~0skqBC8Dr918SMw48FYawznQ5Hf5KawwhtDbl-eGJas4goyqsTSZ8BW~omk1sg3r3ZXgEpnBexE84llfm7HUlRZGLAHSNdZf~exwyn8URACZETPoEY2vff6sgvBmyfnTy5idNthjhaPA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
             'rating' => 7.1,
             'release_date' => '10-08-2023',
             'runtime' => "2h 48m",
             'theatres' => "",
             'ott_platform' => "2",
             'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.e6c3bee4-fea9-4d10-ac7b-61dd7f026d47",
             'imdb_id' => "tt11663228",
             'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt11663228",
            ],

            [
                'movie_name'=> "Gran Turismo",
                'genres' => json_encode([1,10,11,5]),
                'director' => "Neill Blomkamp",
                'producers' => "Columbia Pictures, PlayStation Productions, 2.0 Entertainment",
                'writters' => "Jason Hall, Zach Baylin, Alex Tse",
                'actors' => "David Harbour,Orlando Bloom,Archie Madekwe,Takehiro Hira,Geri Horner",
                'description' => "Jann is an avid gamer from Cardiff who spends his days playing Gran Turismo, refusing to succeed in the real world. Meanwhile, in Tokyo, Danny, a marketing manager for the Nissan automobile corporation, is running an advertising campaign and, together with the management of Gran Turismo, hatches a plan to launch a competition inviting gamers to try their luck in real racing cars. Needing help organizing an event, Danny turns to Jack, a former racing driver and incorrigible cynic. When fate brings Jann together with Danny and Jack, the gamer becomes the driver of a Nissan racing car, plunging headlong into the fight for a place in the sun in the competitive world of real racing.",
                'movie_image' => "images/gran-turismo.jpg",	
                'trailer_link' => "https://imdb-video.media-imdb.com/vi2506277913/1434659607842-pgv4ql-1683038216324.mp4?Expires=1697172235&Signature=MdA5XassB70sJX-XabeSzStzmb2Sppwk~4VhCJ8q-W~FHRenOll1AD~ZGu5If1FcA9V2HAZNpO8u4mHi-tstRg4HE7xA0NqvKtV20i1f7~XgURaOUB4uzjmnuN1YiopgSJRqH4XLAbnQdmvevXzD7mwx568SUJYiqs9zT4lDYn3SxfkXfao73e6HGIGrQoGmmr~kk7H6njvP8F-PO98tqaLSEy62JGgc6smwHHgf2YGbyrzUqAh2zi-8nnxfZ2q9Eah9EnBqu0zoUm4~Fro7KXwyjwLX~JzlmqWZQETG0TpZAQdPU8vnHb6VwGYqkw14CJC9PeGco26pE5hgp06hVg__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
                'rating' => 7.2,
                'release_date' => '09-08-2023',
                'runtime' => "2h 14m",
                'theatres' => "",
                'ott_platform' => "",
                'ott_link' => "",
                'imdb_id' => "tt4495098",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt4495098",
               ],

               [
                'movie_name'=> "Transformers: Dark of the Moon",
                'genres' => json_encode([1,10,12]),
                'director' => "Michael Bay",
                'producers' => "Columbia Pictures, PlayStation Productions, 2.0 Entertainment",
                'writters' => "Ehren Kruger",
                'actors' => "Shia LaBeouf, Rosie Huntington-Whiteley, Tyrese Gibson",
                'description' => "Autobots Bumblebee, Ratchet, Ironhide, Mirage (aka Dino), Wheeljack (aka Que) and Sideswipe led by Optimus Prime, are back in action taking on the evil Decepticons, who are eager to avenge their recent defeat. The Autobots and Decepticons become involved in a perilous space race between the United States and Russia to reach a hidden Cybertronian spacecraft on the moon and learn its secrets, and once again Sam Witwicky has to go to the aid of his robot friends. The new villain Shockwave is on the scene while the Autobots and Decepticons continue to battle it out on Earth.",
                'movie_image' => "images/transformers-dark-of-the-moon.jpg",	
                'trailer_link' => "https://imdb-video.media-imdb.com/vi543989017/1434659607842-pgv4ql-1616202690635.mp4?Expires=1697182471&Signature=lhuHyoevtS8sd3-v9KrOUw0AYoTliBBVAEM5IutV5ZpuYKYPaHN5TnfuVoOg4To47MMR85xiQNp4--fyFjJIFglTe0XYjBxqdhAsVMVXGUzDujTXfi1I5GL3-6EFWBxyEyjqFlDMiJbdpddGMogjNpEQQO2rXWzEb-~IM9~7F7LIgy1DS~aQF~RNMEDCdqh06MbC8I~KTLaPSmrSdeAx1uP10h7TUdd4ZfKdMfGBAf7spOGdFx2AhmE~9z6YG-I1Rv5ZFE~HH8eDJjXfqwcjlVpIu5Ec~1xM4-6z6s~8K3uJjoI1roNhiaXoUKhbsQOETi2NaG0rlV4bp9iChlOpJg__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
                'rating' => 6.2,
                'release_date' => '29-06-2011',
                'runtime' => "2h 34m",
                'theatres' => "",
                'ott_platform' => "2",
                'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.aaabfc06-ca90-da84-b8a8-04a8380f9756",
                'imdb_id' => "tt1399103",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt1399103",
               ],

               [
                'movie_name'=> "Avatar: The Way of Water",
                'genres' => json_encode([1,10,6,12]),
                'director' => "James Cameron",
                'producers' => "Columbia Pictures, PlayStation Productions, 2.0 Entertainment",
                'writters' => "James Cameron, Rick Jaffa, Amanda Silver",
                'actors' => "Sam Worthington, Zoe Saldana, Sigourney Weaver",
                'description' => "Pandora, 2170. Having found meaning and purpose in the heart of the extrasolar Garden of Eden, formerly paraplegic Marine veteran Jake Sully and his fierce warrior princess companion Neytiri enjoy peace and prosperity after the life-altering events of Avatar (2009). But happiness is fleeting. And when the unsightly ghosts of Sully's past emerge, sixteen years after the all-out Assault on the Tree of Souls, the human Toruk Makto and the Na'vi must fight back. Now, Jake and the Omatikaya clan have no choice but to pick up where they left off to defend their home. In the upcoming war against the unstoppable Sky People, will blind revenge destroy everything Sully holds dear?",
                'movie_image' => "images/avatar2.jpg",	
                'trailer_link' => "https://imdb-video.media-imdb.com/vi3565864217/1434659607842-pgv4ql-1669124569701.mp4?Expires=1697180636&Signature=VyRf39b7coKCxTnVWCdFfbG46zcndWHOyPKWpBpeur8TSEftdFtO-kCH7C92GpsNO637NswT6JDsQim7I9Z6vbflSkQCi0vlqbXWISCk1-Mlg6vqpTuz7HCHaQjO5jpuC0hmuY7hAMuuaYOajtzy9RA53vhaMNUJvZH5ylYLzp97nJb9dYupOd7ho4hTFhmRKUV6AdVh~iiDTh2xgVDNpp0zrKChi3PnLmb9Mb2fFpntAOobfjLwJPb0ONaBfjsntr9lY8pPHnSmKSgYZyJUVKQhe2SEQ1nj2fI8B1y5zagYBQWU5-xp1UsrkLjuLvksijTnbRC0XMyMC7jETUf9NA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
                'rating' => 7.6,
                'release_date' => '16-12-2022',
                'runtime' => "3h 12m",
                'theatres' => "",
                'ott_platform' => "3",
                'ott_link' => "https://www.hotstar.com/in/paywall?content_id=1260142021&content_title=Avatar%3A+The+Way+of+Water&content_type=MOVIE&failed_pc_entitlement_context=%7B%22playback_list_platforms%22%3A%22web%22%2C%22tags%22%3A%22vip%2Cpaid%22%7D&failed_pc_entitlement_required=%5B%22tags%22%2C%22playback_list_platforms%22%5D&is_content_paid=true&utm_source=gwa",
                'imdb_id' => "tt1630029",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt1630029",
               ],

               [
                'movie_name'=> "After",
                'genres' => json_encode([5,4]),
                'director' => "Jenny Gage",
                'producers' => "CalMaple, Wattpad, Diamond Film Productions",
                'writters' => "Susan McMartin, Tamara Chestna,Jenny Gage",
                'actors' => "	Josephine Langford,Hero Fiennes Tiffin, Khadijha Red Thunder, Dylan Arnold",
                'description' => "Based on Anna Todd's novel, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter, and loyal girlfriend to her high-school sweetheart, as she enters her first semester in college armed with grand ambitions for her future. Her guarded world opens up when she meets the dark, mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants from life.",
                'movie_image' => "images/After.jpg",	
                'trailer_link' => "https://imdb-video.media-imdb.com/vi191412761/1434659607842-pgv4ql-1550169864182.mp4?Expires=1697183124&Signature=ZgUohaW89SJD4uILQaHI8RjwrEH3dxXIj~H1RqKboDDKMQ1NkwksB5E2W-sJlgseoSpJV2tp2I-3wz2B81J-DDtr0A5KgGcQ10~w51GG~V2VLvoPvXk1zjY99uJv2GQQnLXbgM1B5HUHDHCEtyz7jePX1cFaY~VtOu4yMBla1p609OWs54DSHBcUWcMUpVPfS~bGWG04lzgn1dLkfFFB-58lPLk5cLhjMf4MmeoVNia3XV4GBSvUFiJedlrPN0TBCfBrVxr31MoXv8osc0TnVY-F4xbmyLWapNLXDQnwQrRJyENUN~Oq7KuerYAeWNvVxyNlKtMq7yfFkWxITJ2cIQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
                'rating' => 5.3,
                'release_date' => '12-07-2019',
                'runtime' => "1h 45m",
                'theatres' => "",
                'ott_platform' => "2",
                'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.467955de-3bc4-4943-bea0-1dd33cce7e20",
                'imdb_id' => "tt4126476",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt4126476",
               ],

               [
                'movie_name'=> "Fifty Shades of Grey",
                'genres' => json_encode([5,4,3]),
                'director' => "Sam Taylor-Johnson",
                'producers' => "Focus Features, Michael De Luca Productions, Trigger Street Productions",
                'writters' => "Kelly MarcelE.L. James",
                'actors' => "Dakota Johnson, Jamie Dornan, Jennifer Ehle",
                'description' => "Anastasia Steele, an English literature major at Washington State University, agrees to interview for the college newspaper a billionaire, Christian Grey, as a favour to her roommate, Kate Kavanagh. During the interview, Christian Grey takes an interest in Anastasia. Soon after it, he visits the hardware store where Anastasia works and offers her to do a photo shoot to accompany the article for which Anastasia had interviewed him. Later, Grey invites her to a cafe and also sends her first edition copies of two Thomas Hardy novels, including Tess of the d'Urbervilles, with a quote from the latter book about the dangers of relationships, on an accompanying card. His pursuing eventually brings a result - Anastasia and Grey start dating. In the course of their troubled relationship Anastasia slowly comes to uncover Grey's troubled past and realises that he is not good for any woman, let alone for himself. Although, she enjoys the bondage sex with Grey, she feels that she has to make a step that will take her all her strength and courage, for Christian Grey is a very dangerous man",
                'movie_image' => "images/fifty-shades-of-grey.jpg",	
                'trailer_link' => "https://imdb-video.media-imdb.com/vi651013145/MV5BMjI0MjMxODU3Ml5BMTFeQW1wNF5BbWU4MDcwMTM4MjIx.mp4?Expires=1697183851&Signature=nG5xNjXJnmsQsTFUWoxd1kn-OplVmyIxp2EpQ2ffEleJq5UzhoYYIeMHElmdWIWkAGAz6C7gsXNUjPc9~54eyaSqmmN3nNLl-jQjo8joel7VMnqZ5o6chbKW-LKm4625VBiIOZBQtydSvwdZ4qtV4dBpwVj4TGrqkiCljWtDbLaj-0BwfLf2DZXOjuhXZ6wC-IJ1mBUG7HS0bW9lJN8fMLfVgy2i-hvVPhGO9TMepu1qcfSL95SWwRzABUARPTPMubYe-FPSo5NsByUwnVz0Czh2vtg~ZJk1M9bMxys9wySYS50A1fJjOblrYVS-qAmkD0V81rnRE3xhcnQZjE2tLA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA",	
                'rating' => 4.2,
                'release_date' => '13-02-2015',
                'runtime' => "2h 5m",
                'theatres' => "",
                'ott_platform' => "1",
                'ott_link' => "https://www.netflix.com/in/title/80013872?source=imdb",
                'imdb_id' => "tt2322441",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt2322441",
               ],

               [
                'movie_name'=> "100 Days of Love",
                'genres' => json_encode([8,4]),
                'director' => "Jenuse Mohamed",
                'producers' => "Kanuj Bhatia, Shafeer Sait",
                'writters' => "Suhail Ibrahim, Jenuse Mohamed, M.R. Vibin",
                'actors' => "Dulquer SalmaanNithya MenenSekhar Menon",
                'description' => "A beautiful Love story where a guy named Balan( Dulquer Salmaan) has a break up with his girl friend and there break up some how becomes viral on social media. As he was trying to over come the stress of break up he meets Sheela(Nithya Menen) in a Taxi, But in a rush she drops her old digital camera which Balan picks up and tries to return to her with a help of his friend Ummer. Finally when he finds her, She (Sheela) tells him that she is his (Balaan) school mate with whom he had a huge fight. Balaan gets over the past and invites her to a new year eve dinner and returns the camera to her. She explains why this camera is so important to her and she is making a 25th anniversary surprise for her parents in which Balaan also helps. Balaan find out sheela is with a boyfriend named Rahul and she get engaged with Rahul. Eventually Balaan convinced her(Sheela) that she believes in love and to choose him over Rahul. Sheela falls in love with Balan at the end and gets married with him. Though the story is nothing new but the direction, songs, story telling and cinematography amazes the viewers and keeps them attached to the end.",
                'movie_image' => "images/100daysoflove.jpg",	
                'trailer_link' => "https://imdb-video-wab.media-imdb.com/vi947894297/1434659607842-pgv4ql-1523443170487.mp4?Expires=1697186958&Signature=EFofXNQpsvlQj8xoxV47VDPcJOEiNfxSl1GPML5KzPBsx8qUTE8x8Bytb6XcKT5aIlsDAXlYVrIRGjygGGg4p2jFbhMIew5VK6oMG1LaGfZDE2jrEgJfzI9oiqBpdBsEfVEm4mwWbTvLgVE6T9fPNojSDLvOeD3a~0ECr~tb0WKLTb-7Lh4EzD8ZRYHzGn2WlayAfu7h~x9tgkawbayzvDifDt87~ZCRKQjReTU-sIyVuxcB-S~JLpjD~R~U4CAOC8RQ4nAYvIvxFcbOBFHtkgX51q-g7dPeN4mX92tEwQK9q4USzNncTHH1VMW4ilcJRKAfGuv3wo798g70-7RScA__&Key-Pair-Id=APKAJLOTGGE6P3RA3PTA",	
                'rating' => 6.6,
                'release_date' => '13-02-2015',
                'runtime' => "2h 33m",
                'theatres' => "",
                'ott_platform' => "",
                'ott_link' => "",
                'imdb_id' => "tt3995348",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt3995348",
               ],

               [
                'movie_name'=> "Theri",
                'genres' => json_encode([1,9,3]),
                'director' => "Atlee",
                'producers' => "Kanuj Bhatia, Shafeer Sait",
                'writters' => "Atlee, Ramanagirivasan, Rishabh Purohit",
                'actors' => "Joseph Vijay, Samantha Ruth Prabhu, Amy Jackson",
                'description' => "When an honest cop, Vijay Kumar's family is ruthlessly slaughtered by a politician and his aides, he decides to change his identity and commits his life to bring his daughter up in a serene atmosphere. But some freak events end up compromising his identity and what he does to save his daughter and avenge the death of his family unfurls as Theri.",
                'movie_image' => "images/theri.jpg",	
                'trailer_link' => "https://imdb-video-wab.media-imdb.com/vi3048519705/1434659607842-pgv4ql-1510519259386.mp4?Expires=1697188549&Signature=eDDDQnAL3UQyQxI~Am~ohopCcQFA6R4GmZSXHmOPbjzrBpV2POSIdR805rjgIX0zpTktxaz4pQtP2ih2u-yLVhJIvpIjhLrZQmRsFXUr~KVdttk8tHOSdaa-P~GVIpqwRyOd8SZFKgALpYnPrTfwuxmf2PyQrxr7bLFlraHuO4riLDicogKJMG2gbKTxTehAgLW6-xx2iZSuJtbOdduiYqWHcbH0sGEmEq2YxgQHyP3LRBUdz88htnBDyt6UCtiBcjPIdhea8AQFPwi9jwKbfoIdaV1vqxCLXA6JVYxxTHwaFmyZANmzdOJQi4iAgAkyCrbjdTS~xdfr968Om3rPcg__&Key-Pair-Id=APKAJLOTGGE6P3RA3PTA",	
                'rating' => 7.3,
                'release_date' => '15-04-2016',
                'runtime' => "2h 37m",
                'theatres' => "",
                'ott_platform' => "2",
                'ott_link' => "https://www.primevideo.com/detail/amzn1.dv.gti.e4b6e08a-d0c0-da3b-2d92-0d4a91162610",
                'imdb_id' => "tt5440700",
                'movie_link'=>"https://embed.smashystream.com/playere.php?imdb=tt5440700",
               ],
        ]);
    }
}
